# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(171, 681)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_vu2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_vu2.setObjectName("pushButton_vu2")
        self.verticalLayout.addWidget(self.pushButton_vu2)
        self.pushButton_pa2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pa2.setObjectName("pushButton_pa2")
        self.verticalLayout.addWidget(self.pushButton_pa2)
        self.pushButton_ni2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ni2.setObjectName("pushButton_ni2")
        self.verticalLayout.addWidget(self.pushButton_ni2)
        self.pushButton_zo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_zo.setObjectName("pushButton_zo")
        self.verticalLayout.addWidget(self.pushButton_zo)
        self.pushButton_ke = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ke.setObjectName("pushButton_ke")
        self.verticalLayout.addWidget(self.pushButton_ke)
        self.pushButton_di = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_di.setObjectName("pushButton_di")
        self.verticalLayout.addWidget(self.pushButton_di)
        self.pushButton_ga = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ga.setObjectName("pushButton_ga")
        self.verticalLayout.addWidget(self.pushButton_ga)
        self.pushButton_vu = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_vu.setObjectName("pushButton_vu")
        self.verticalLayout.addWidget(self.pushButton_vu)
        self.pushButton_pa = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_pa.setObjectName("pushButton_pa")
        self.verticalLayout.addWidget(self.pushButton_pa)
        self.pushButton_ni = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ni.setObjectName("pushButton_ni")
        self.verticalLayout.addWidget(self.pushButton_ni)
        self.pushButton_zo0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_zo0.setObjectName("pushButton_zo0")
        self.verticalLayout.addWidget(self.pushButton_zo0)
        self.pushButton_ke0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ke0.setObjectName("pushButton_ke0")
        self.verticalLayout.addWidget(self.pushButton_ke0)
        self.pushButton_di0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_di0.setObjectName("pushButton_di0")
        self.verticalLayout.addWidget(self.pushButton_di0)
        self.pushButton_ga0 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ga0.setObjectName("pushButton_ga0")
        self.verticalLayout.addWidget(self.pushButton_ga0)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout.addWidget(self.comboBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 2)
        self.pushButton_stop = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.gridLayout.addWidget(self.pushButton_stop, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 171, 29))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionExit)
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Byz Ison"))
        self.pushButton_vu2.setText(_translate("MainWindow", "Vu\'"))
        self.pushButton_pa2.setText(_translate("MainWindow", "Pa\'"))
        self.pushButton_ni2.setText(_translate("MainWindow", "Ni\'"))
        self.pushButton_zo.setText(_translate("MainWindow", "Zo"))
        self.pushButton_ke.setText(_translate("MainWindow", "Ke"))
        self.pushButton_di.setText(_translate("MainWindow", "Di"))
        self.pushButton_ga.setText(_translate("MainWindow", "Ga"))
        self.pushButton_vu.setText(_translate("MainWindow", "Vu"))
        self.pushButton_pa.setText(_translate("MainWindow", "Pa"))
        self.pushButton_ni.setText(_translate("MainWindow", "<Ni>"))
        self.pushButton_zo0.setText(_translate("MainWindow", "Zo,"))
        self.pushButton_ke0.setText(_translate("MainWindow", "Ke,"))
        self.pushButton_di0.setText(_translate("MainWindow", "Di,"))
        self.pushButton_ga0.setText(_translate("MainWindow", "Ga,"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Diatonic"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Enharmonic"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Soft Chromatic"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Hard Chromatic"))
        self.pushButton_stop.setText(_translate("MainWindow", "Stop"))
        self.label.setText(_translate("MainWindow", "Frequency"))
        self.menuHelp.setTitle(_translate("MainWindow", "Menu"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
